language: node_js
env:
  global:
    - 'SFTP_USER=[User]'
    - 'SFTP_KEY=[c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFEWURUYVhzTWxYbkU5TlR5c0o1NHJROVBudjJvY3VVcjhkdlR4eGJ6ZFlQajBkZEdWdStQRkJYbjV5b3V2R0pLenZhN1UrM0w3L3k1Yy9yY2FKbnNEVXhZdTFUZG9vVXBpYi85VkhZOGR5WkNrRmNhZHFLNDMzZHVVK2YyejdwY1NBUUd4QzVKQ25QbzNVTmUrWDJjV3lucGlyOEc2UUFjYXhSWm50ckVydVJ0NUZOTmY4RW5VS2NqZUZOOHBXVGJ1S243UzBaNXVXaWhKWWprL3NrbFNFR0NWeG9ZQm9JSmFOOWU5RG5sektObyt0N1U3Rk4vd3dmb2tsY3Riejd4RnBRYVFDdXdadnA4Z2lCcG9IbWtjS0laOXIwYmxpb3BISHZXTW5KRG5CaTYyR0ptNlFBMjg3aWdqVDhVUUIrQW16V2hKZFl6eDRTVjVFSDgwTDBYNHYgTUwtSkFTT05cVXNlckBNTC1KYXNvbg==]'
node_js:
  - "8"
  - "10"
after_success:
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
  - curl --ftp-create-dirs
         -T ./README.md
         --key /tmp/sftp_rsa
         sftp://${SFTP_USER}@35.201.211.232/home/www/temp/