language: node_js
node_js:
  - "8"
  - "10"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - npm i
  - npm i coveralls
script:
  - npm run coverage
after_success:
  - npm run coverage_report
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT