language: node_js
env:
  global:
    - 'SFTP_USER=[User]'
    - 'SFTP_KEY=[base64-encoded-rsa-key]'
node_js:
  - "8"
  - "10"
install:
  - npm i
script:
  - npm run coverage
after_success:
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
  - curl --ftp-create-dirs
         -T README.md
         --key /tmp/sftp_rsa
         sftp://${SFTP_USER}@35.201.211.232/home/www/temp/